name: Build and Push Camel Native Image

on:
  push:
    paths:
      - 'csv-json.camel.yaml'

jobs:
  build-native-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install JBang
      run: |
        curl -Ls https://sh.jbang.dev | bash -s - app setup
        echo "$HOME/.jbang/bin" >> $GITHUB_PATH

    - name: Install Camel extension for JBang
      run: |
        jbang trust add https://github.com/apache/
        jbang app install --quiet camel@apache/camel

    - name: Build Native Image with Camel JBang
      run: |
        camel export --native csv-json.camel.yaml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Dockerfile
      run: |
        cat > Dockerfile << 'EOF'
        FROM scratch
        COPY csv-json.camel.yaml.native /app
        ENTRYPOINT ["/app"]
        EOF

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ steps.repo-name.outputs.REPO_NAME }}/camel-csv-json:latest
          ghcr.io/${{ steps.repo-name.outputs.REPO_NAME }}/camel-csv-json:${{ github.sha }}
