name: Build and Push Camel Spring Boot Native Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'csv-json.camel.yaml'

jobs:
  build-native-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install JBang
      run: |
        curl -Ls https://sh.jbang.dev | bash -s - app setup
        echo "$HOME/.jbang/bin" >> $GITHUB_PATH

    - name: Install Camel extension for JBang
      run: |
        jbang trust add https://github.com/apache/
        jbang app install --quiet camel@apache/camel

    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Export to Spring Boot
      run: |
        camel export --runtime=spring-boot --gav=de.predic8:camel-jbang-pipeline:1.0.0 csv-json.camel.yaml
        
    - name: Build Native Image with Spring Boot
      run: |
        cd csv-json
        ./mvnw -Pnative spring-boot:build-image -Dnative

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and Push Docker Image
      run: |
        cd csv-json
        
        docker tag de.predic8:camel-jbang-pipeline:1.0.0 ghcr.io/${{ steps.repo-name.outputs.REPO_NAME }}/camel-jbang-pipeline:latest
        docker tag de.predic8:camel-jbang-pipeline:1.0.0 ghcr.io/${{ steps.repo-name.outputs.REPO_NAME }}/camel-jbang-pipeline:${{ github.sha }}
        
        docker push ghcr.io/${{ steps.repo-name.outputs.REPO_NAME }}/camel-jbang-pipeline:latest
        docker push ghcr.io/${{ steps.repo-name.outputs.REPO_NAME }}/camel-jbang-pipeline:${{ github.sha }}
